name: Release workflow

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - uses: ncipollo/release-action@v1
        with:
          tag: ops-latest

  tests:
    name: Run test suite
    runs-on: ubuntu-latest
        
    steps:
      - name: Run test suite
        run: echo "Executing test suite ✅"

  promote-artifact:
    name: Promote artifact
    runs-on: ubuntu-latest
    needs: create-github-release

    steps:
      - name: Promote artifact
        run: echo "Promoting artifact ✅"

  create-octopus-release:
    name: Create Octopus Release 🐙
    runs-on: ubuntu-latest
    needs: promote-artifact
      
    env:
      OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
      OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      OCTOPUS_SPACE: ${{ secrets.OCTOPUS_SPACE_NAME }}
        
    steps:
      - uses: OctopusDeploy/create-release-action@v3
        id: "create-release"
        with:
          project: "OctoPetShop - Gitflow 1"
          channel: "2 - Release"

